name: web_barry_callebaut
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^1.13.1
  firebase_auth: ^3.3.9
  cloud_firestore: ^3.1.10
  intl: ^0.17.0
  provider: ^6.0.2
  flutter_riverpod: ^1.0.3

  flutter_svg: ^1.0.3
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/logo.svg
    - assets/icon1.svg
    - assets/icon2.svg
    - assets/icon3.svg
    - assets/icon4.svg
    - assets/icon5.svg
    - assets/pin.png
    - assets/admin.svg
    - assets/koordinator.svg
    - assets/petugas.svg
    - assets/petani.svg

  fonts: 
    - family: Poppins
      fonts:
      - asset: fonts/Poppins-Thin.ttf
        weight: 100
      - asset: fonts/Poppins-ExtraLight.ttf
        weight: 200
      - asset: fonts/Poppins-Light.ttf
        weight: 300
      - asset: fonts/Poppins-Regular.ttf
        weight: 400
      - asset: fonts/Poppins-Medium.ttf
        weight: 500
      - asset: fonts/Poppins-SemiBold.ttf
        weight: 600
      - asset: fonts/Poppins-Bold.ttf
        weight: 700
      - asset: fonts/Poppins-ExtraBold.ttf
        weight: 800
      - asset: fonts/Poppins-Black.ttf
        weight: 900
    - family: CustomIcons
      fonts:
      - asset: fonts/CustomIcons.ttf
